# Copyright 2017 Xaptum, Inc.
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License

language: c

compiler:
  - gcc

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y valgrind

  - git submodule update --init --recursive
  - mkdir build
  - cd build

  - mkdir debug-with-coverage
  - cd debug-with-coverage
  - cmake ../.. -DCMAKE_BUILD_TYPE=DebugWithCoverage -DCMAKE_C_OUTPUT_EXTENSION_REPLACE=ON
  - cd ..

  - mkdir release
  - cd release
  - cmake ../.. -DCMAKE_BUILD_TYPE=Release
  - cd ..

  - mkdir memcheck
  - cd memcheck
  - cmake ../.. -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - cd ..

script:
  - cd release
  - cmake --build .
  - ctest -V
  - cd ..

  - cd debug-with-coverage
  - cmake --build .
  - ctest -V
  - cd ..

  - cd memcheck
  - cmake --build .
  - ctest -V -E benchmarks -T memcheck
  - cd ..

after_success:
  - cd debug-with-coverage
  - ../../.travis/upload-gcov-results.sh `pwd`
  - cd ..

  - cd memcheck
  - ../../.travis/show-memcheck-results.sh `pwd`
  - cd ..
